title: sike lipu pi ma pona

collections:
  people:
    output: true
    permalink: /embed/:title

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_people"
    values:
      layout: embed
